# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('source_web', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
            ],
        ),
    ]
